#!/usr/bin/env python3
"""
Script to generate Updates section for app overview pages.
This script reads update files from docs/app/updates/ and generates a preview section
showing the 5 newest updates, which is inserted into docs/app/overview.md and all language variants.
"""

import re
import sys
from pathlib import Path

# Import functions from generate_updates_list.py
script_dir = Path(__file__).parent
sys.path.insert(0, str(script_dir))

from generate_updates_list import (
    get_update_files_info,
    load_language_config,
)


def generate_updates_section_markdown(update_files, language="en", limit=5):
    """Generate markdown section for updates preview."""
    if not update_files:
        return None
    
    # Sort by raw_date in descending order (newest first)
    sorted_updates = sorted(
        update_files,
        key=lambda x: x.get("raw_date") or "",
        reverse=True
    )
    
    # Take top N updates
    top_updates = sorted_updates[:limit]
    
    if not top_updates:
        return None
    
    # Translation keys
    translations = {
        "en": {"section": "Updates", "read_more": "Read more updates"},
        "zh": {"section": "更新", "read_more": "阅读更多更新"},
        "ja": {"section": "更新", "read_more": "更新をもっと読む"},
        "ko": {"section": "업데이트", "read_more": "더 많은 업데이트 읽기"},
        "fr": {"section": "Actualités", "read_more": "Lire plus d'actualités"},
        "de": {"section": "Updates", "read_more": "Weitere Updates lesen"},
        "it": {"section": "Aggiornamenti", "read_more": "Leggi altri aggiornamenti"},
        "es": {"section": "Actualizaciones", "read_more": "Leer más actualizaciones"},
        "pt": {"section": "Atualizações", "read_more": "Ler mais atualizações"},
        "ro": {"section": "Actualizări", "read_more": "Citește mai multe actualizări"},
    }
    
    lang_translations = translations.get(language, translations["en"])
    section_title = lang_translations["section"]
    read_more_text = lang_translations["read_more"]
    
    # Generate markdown
    lines = [
        f"## {section_title}",
        "",
        "<!-- AUTO-GENERATED: This section is automatically generated by scripts/update-post-tool/generate_app_overview_updates.py -->",
        "<!-- DO NOT EDIT MANUALLY -->",
        "",
    ]
    
    for update in top_updates:
        date = update.get("date", "Unknown Date")
        title = update.get("title", "Untitled")
        filename = update.get("filename", "")
        # Use relative path from overview.md to updates/
        link_path = f"updates/{filename}"
        lines.append(f"- {date}: [{title}]({link_path})")
    
    lines.extend([
        "",
        f"[:octicons-arrow-right-24: {read_more_text}](/app/updates)",
        "",
        "<!-- END AUTO-GENERATED -->",
        "",
    ])
    
    return "\n".join(lines)


def insert_updates_section(content, updates_section, language="en"):
    """Insert or replace updates section in overview content."""
    if not updates_section:
        return content
    
    # Translation keys for Updates section header (to match existing section)
    translations = {
        "en": "Updates",
        "zh": "更新",
        "ja": "更新",
        "ko": "업데이트",
        "fr": "Actualités",
        "de": "Updates",
        "it": "Aggiornamenti",
        "es": "Actualizaciones",
        "pt": "Atualizações",
        "ro": "Actualizări",
    }
    updates_section_title = translations.get(language, "Updates")
    
    # Pattern to find ONLY the auto-generated Updates section (very specific)
    # Match: ## Updates (or translated) followed by AUTO-GENERATED comments
    auto_generated_pattern = re.compile(
        rf"## {re.escape(updates_section_title)}\s*\n\s*<!-- AUTO-GENERATED:.*?<!-- END AUTO-GENERATED -->\s*\n",
        re.DOTALL
    )
    
    # Check if Updates section already exists (auto-generated)
    if auto_generated_pattern.search(content):
        # Replace ONLY the existing Updates section, preserve everything else
        return auto_generated_pattern.sub(updates_section + "\n", content)
    
    # If Updates section doesn't exist, find where to insert it
    # Translation patterns for "Download & Installation" section
    download_section_patterns = [
        r"## Download & Installation",  # English
        r"## 下载与安装",  # Chinese
        r"## ダウンロードとインストール",  # Japanese
        r"## 다운로드 및 설치",  # Korean
        r"## Téléchargement et installation",  # French
        r"## Download und Installation",  # German
        r"## Download e installazione",  # Italian
        r"## Descarga e instalación",  # Spanish
        r"## Download e instalação",  # Portuguese
        r"## Descărcare și instalare",  # Romanian
    ]
    
    # Try to find Download & Installation section
    for pattern in download_section_patterns:
        # Look for the section header (must be on its own line)
        header_match = re.search(rf"^{re.escape(pattern)}\s*$", content, re.MULTILINE)
        if header_match:
            # Find where this section ends (after warning section or next ##)
            start_pos = header_match.end()
            after_header = content[start_pos:]
            
            # Find the warning section that comes after Download & Installation
            # Look for ???+ warning block followed by blank lines
            warning_match = re.search(r"\?\?\?\+.*?\n\n+", after_header, re.DOTALL)
            if warning_match:
                # Insert after warning section (preserve all content)
                insert_pos = start_pos + warning_match.end()
                return content[:insert_pos] + "\n" + updates_section + "\n" + content[insert_pos:]
            else:
                # Find the next ## section (but don't match Updates if it exists)
                next_section_match = re.search(r"^## (?!{})".format(re.escape(updates_section_title)), after_header, re.MULTILINE)
                if next_section_match:
                    # Insert before next section (preserve all content)
                    insert_pos = start_pos + next_section_match.start()
                    return content[:insert_pos] + "\n" + updates_section + "\n" + content[insert_pos:]
                else:
                    # Insert at end of Download & Installation section content
                    insert_pos = start_pos + len(after_header)
                    return content[:insert_pos] + "\n" + updates_section + "\n" + content[insert_pos:]
    
    # Fallback: if Download & Installation section not found, append at end
    # This preserves all existing content
    return content + "\n\n" + updates_section


def process_overview_file(overview_path, updates_dir, language="en"):
    """Process a single overview file and update it with updates section."""
    if not overview_path.exists():
        print(f"⚠️  Overview file not found: {overview_path}")
        return False
    
    # Get update files for this language
    update_files = get_update_files_info(updates_dir, language)
    
    # Generate updates section
    updates_section = generate_updates_section_markdown(update_files, language, limit=5)
    
    if not updates_section:
        print(f"⚠️  No updates found for {language}, skipping {overview_path.name}")
        return False
    
    # Read current content
    with open(overview_path, "r", encoding="utf-8") as f:
        content = f.read()
    
    # Insert or replace updates section
    new_content = insert_updates_section(content, updates_section, language)
    
    # Write back
    with open(overview_path, "w", encoding="utf-8") as f:
        f.write(new_content)
    
    return True


def main():
    """Main function to generate updates sections for all overview files."""
    script_dir = Path(__file__).parent
    project_root = script_dir.parent.parent
    docs_dir = project_root / "docs"
    app_dir = docs_dir / "app"
    updates_dir = app_dir / "updates"
    
    if not updates_dir.exists():
        print(f"⚠️  Updates directory not found: {updates_dir}")
        print("   Skipping overview updates generation.")
        return
    
    # Load language configuration
    default_language, supported_languages = load_language_config()
    
    print("=" * 70)
    print("Generating Updates Section for App Overview Pages")
    print("=" * 70)
    
    success_count = 0
    total_count = 0
    
    # Process each language
    for language in supported_languages:
        total_count += 1
        
        # Determine overview file path
        if language == default_language:
            overview_path = app_dir / "overview.md"
        else:
            overview_path = app_dir / f"overview.{language}.md"
        
        print(f"\n🌍 Processing {language}...")
        
        if process_overview_file(overview_path, updates_dir, language):
            print(f"✅ Updated {overview_path.name}")
            success_count += 1
        else:
            print(f"⚠️  Skipped {overview_path.name}")
    
    print("\n" + "=" * 70)
    print(f"✅ Completed: {success_count}/{total_count} overview files updated")
    print("=" * 70)


if __name__ == "__main__":
    main()

