title: Product
nav:
    - index.md
    - Mini-KVM:
        - minikvm/index.md
        - minikvm/whats-in-the-box.md
        - minikvm/features.md
        - ../app/basic.md
        - minikvm/how-to-connect.md
        - How It Works: /faq/usbkvm/kvm-over-usb/
        - Reviews & Press: minikvm/reviews.md
        - minikvm/specifications.md
        - minikvm/usb-switch.md
        - minikvm/extension-pins.md
        - FAQs & Troubleshoot: /faq/minikvm/op-minikvm/
        - Why Openterface: /faq/usbkvm/openterface/
    - Mini-KVM Lite (Pre-Launch):
        - minikvm-lite/pre-launch.md
    - Accessories:
        - accessories/index.md
        - VGA to HDMI Cable 1m: accessories/vga-to-hdmi-cable.md
        - Type-C to C Cable Nylon 1.5m: accessories/nylong-c-to-c-150.md
        - Type-C to C Cable Orange 1.5m: accessories/type-c-to-c-cable-with-adapter.md
        - Type-C to A Cable Black 30cm: accessories/black-c-to-a-30.md
        - HDMI Cable 30cm: accessories/hdmi-male-to-male-cable.md
        - Toolkit Bag: accessories/openterface-toolkit-bag.md